import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import { Caveat } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const caveat = Caveat({
  weight: "400",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body className={caveat.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
