import type { Metadata } from "next";
import { Caveat } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/ThemeProvider";

const caveat = Caveat({
  weight: "400",
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body className={caveat.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
